version: "3.9"

networks:
  chatpdf-network:
    driver: bridge
    name: chatpdf-network

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend   

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend   